---
destination:
  elasticsearch:
    host: localhost
    username: kene
    password: pssword_kene@
sources:
  files:
    logs:
      - name: syslog
        path: "/var/log/syslog/*.log"
      - name: messages
        path: "/var/log/messages/*.log"
      - name: auth
        path: "/var/log/auth.log"
